### ISSUE TITLE
X11 isolation using Xpra

### ISSUE THREAD

**Issue by xmikos** [thestinger/playpen#54]
Can you add support for X11 isolation using [Xpra](https://www.xpra.org)? You can look for example how [Oz sandbox](https://github.com/subgraph/oz) from Subgraph OS is doing it. Without X isolation, any app can easily broke out of sandbox (listen to key presses in other apps, etc.).

**Comment by thestinger** [comment]
> Without X isolation, any app can easily broke out of sandbox (listen to key presses in other apps, etc.).

Playpen isn't aimed at sandboxing graphical applications right now though. It doesn't make any decisions about it at all.

> Can you add support for X11 isolation using Xpra

It's likely not how X11 support would be approached if it was implemented. The desire would be for the X11 instance to be specific to the application and sandboxed alongside it (i.e. Xephyr, not Xpra). It's not particularly interesting to me though because Wayland already works well and Playpen targets bleeding edge systems. The only reason I'm not already using Wayland myself is the fact that there isn't a full port of i3-wm to it.
