### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by pete3215** [thestinger/playpen#67]
Is this project still maintained?
There has not been any activity for over a year.

**Comment by thestinger** [comment]
It provides what it was written to do already. It's not really intended to be a more general purpose project with networking, support for desktop applications (which would require dealing with dbus / pulseaudio filtering, etc.) and unprivileged use. There aren't any known bugs so there's not really any to do, since adding more features isn't really desired right now. There are things like https://github.com/projectatomic/bubblewrap now for more complex use.

**Comment by pete3215** [comment]
Thanks for the quick response.
Maybe you want to respond to the other issues as well to clarify the things mentioned here.
